/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quizango;

import java.awt.Color;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ram
 */
public class adminmenu extends javax.swing.JFrame {
    private String qname;

    /**
     * Creates new for
     */
    public adminmenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        create = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        check = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        delete = new javax.swing.JButton();
        adminlogopanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        createquiz = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        quizname = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        checkscore = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        scorecombo = new javax.swing.JComboBox();
        deletequiz = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        deletecombo = new javax.swing.JButton();
        scorecombo1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(96, 223, 170));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 204, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, 50, 40));

        jLabel4.setFont(new java.awt.Font("Gisha", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LetsQUIZ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 40));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1100, 40);

        jPanel4.setBackground(new java.awt.Color(0, 204, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMIN");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 270, -1));

        jPanel6.setBackground(new java.awt.Color(255, 102, 102));

        create.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        create.setForeground(new java.awt.Color(255, 255, 255));
        create.setText("CREATE QUIZ");
        create.setContentAreaFilled(false);
        create.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(create, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(create, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 270, 40));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizango/icons8-admin-settings-male-64.png"))); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 270, 100));

        jPanel8.setBackground(new java.awt.Color(255, 102, 102));

        check.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        check.setForeground(new java.awt.Color(255, 255, 255));
        check.setText("CHECK SCORE");
        check.setContentAreaFilled(false);
        check.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(check)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 270, 40));

        jPanel7.setBackground(new java.awt.Color(255, 102, 102));

        delete.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("DELETE QUIZ");
        delete.setContentAreaFilled(false);
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 270, 40));

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 90, 270, 410);

        adminlogopanel.setBackground(new java.awt.Color(0, 204, 153));
        adminlogopanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon("H:\\Downloads\\4c7e734e-caca-4a66-afa1-579f9e3fd737_200x200.png")); // NOI18N
        adminlogopanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 410));

        jPanel1.add(adminlogopanel);
        adminlogopanel.setBounds(410, 90, 690, 410);

        createquiz.setBackground(new java.awt.Color(0, 204, 153));
        createquiz.setVisible(false);
        createquiz.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizango/icons8-create-64.png"))); // NOI18N
        createquiz.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 110, 70));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CREATE QUIZ");
        createquiz.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 229, 170, 30));

        jLabel9.setFont(new java.awt.Font("Tekton Pro", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Enter Name of Quiz");
        createquiz.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));

        quizname.setBackground(new java.awt.Color(0, 204, 153));
        quizname.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        quizname.setForeground(new java.awt.Color(255, 102, 102));
        quizname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        quizname.setBorder(null);
        quizname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quiznameActionPerformed(evt);
            }
        });
        createquiz.add(quizname, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 260, 40));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("________________________");
        createquiz.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 270, 30));

        jPanel9.setBackground(new java.awt.Color(255, 102, 102));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Create");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 40));

        createquiz.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 190, 40));

        jPanel1.add(createquiz);
        createquiz.setBounds(410, 90, 690, 410);

        checkscore.setBackground(new java.awt.Color(0, 204, 153));
        checkscore.setVisible(false);
        checkscore.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizango/icons8-total-sales-96.png"))); // NOI18N
        checkscore.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 130, 90));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CHECK SCORE");
        checkscore.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 229, 170, 30));

        jLabel10.setFont(new java.awt.Font("Tekton Pro", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Select Quiz");
        checkscore.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, -1));

        jPanel10.setBackground(new java.awt.Color(255, 102, 102));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Check");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 40));

        checkscore.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 190, 40));

        scorecombo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        scorecombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Quiz", "scheck" }));
        scorecombo.setBorder(null);
        try{
            scorecombo.removeAllItems();
            Class.forName("com.mysql.jdbc.Driver");
            java.sql.Connection con=DriverManager.getConnection( "jdbc:mysql://localhost:3306/admin?zeroDateTimeBehavior=convertToNull","root","12345");
            java.sql.Statement stmt=con.createStatement();
            ResultSet rs = null;
            rs = stmt.executeQuery("SELECT table_name FROM information_schema.tables where table_schema='admin';");
            while (rs.next()){
                String nm = rs.getString("table_name");
                scorecombo.addItem(nm);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Sorry!");
        }
        scorecombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scorecomboMouseClicked(evt);
            }
        });
        scorecombo.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                scorecomboComponentAdded(evt);
            }
        });
        scorecombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scorecomboActionPerformed(evt);
            }
        });
        checkscore.add(scorecombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 260, 40));

        jPanel1.add(checkscore);
        checkscore.setBounds(410, 90, 690, 410);

        deletequiz.setBackground(new java.awt.Color(0, 204, 153));
        deletequiz.setVisible(false);
        deletequiz.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizango/icons8-delete-bin-128.png"))); // NOI18N
        deletequiz.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 130, 130));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("DELETE QUIZ");
        deletequiz.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 229, 170, 30));

        jLabel12.setFont(new java.awt.Font("Tekton Pro", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Select Quiz to Delete");
        deletequiz.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));

        jPanel11.setBackground(new java.awt.Color(255, 102, 102));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deletecombo.setBackground(new java.awt.Color(255, 255, 255));
        deletecombo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        deletecombo.setForeground(new java.awt.Color(255, 255, 255));
        deletecombo.setText("Delete");
        deletecombo.setBorderPainted(false);
        deletecombo.setContentAreaFilled(false);
        deletecombo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deletecombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletecomboMouseClicked(evt);
            }
        });
        deletecombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletecomboActionPerformed(evt);
            }
        });
        jPanel11.add(deletecombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 40));

        deletequiz.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 190, 40));

        scorecombo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        scorecombo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Quiz" }));
        scorecombo1.setBorder(null);
        try{
            scorecombo1.removeAllItems();
            Class.forName("com.mysql.jdbc.Driver");
            java.sql.Connection con=DriverManager.getConnection( "jdbc:mysql://localhost:3306/admin?zeroDateTimeBehavior=convertToNull","root","12345");
            java.sql.Statement stmt=con.createStatement();
            ResultSet rs = null;
            rs = stmt.executeQuery("SELECT table_name FROM information_schema.tables where table_schema='admin';");
            while (rs.next()) {
                String nm = rs.getString("table_name");
                scorecombo1.addItem(nm);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Something Went Wrong!");
        }
        scorecombo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scorecombo1MouseClicked(evt);
            }
        });
        scorecombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scorecombo1ActionPerformed(evt);
            }
        });
        scorecombo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                scorecombo1KeyPressed(evt);
            }
        });
        deletequiz.add(scorecombo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 260, 40));

        jPanel1.add(deletequiz);
        deletequiz.setBounds(410, 90, 690, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1100, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        createquiz.setVisible(true);
        deletequiz.setVisible(false);
        checkscore.setVisible(false);
        adminlogopanel.setVisible(false);
    }//GEN-LAST:event_createActionPerformed

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
        createquiz.setVisible(false);
        deletequiz.setVisible(false);
        checkscore.setVisible(true);  
        adminlogopanel.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_checkActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        createquiz.setVisible(false);
        deletequiz.setVisible(true);
        checkscore.setVisible(false);
        adminlogopanel.setVisible(false);
    }//GEN-LAST:event_deleteActionPerformed

    private void quiznameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quiznameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quiznameActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        String qname = quizname.getText();
     
        
            try{  
                Class.forName("com.mysql.jdbc.Driver");  
                java.sql.Connection con=DriverManager.getConnection( "jdbc:mysql://localhost:3306/admin?zeroDateTimeBehavior=convertToNull","root","1234");  
                //here sonoo is database name, root is username and password  
                java.sql.Statement stmt=con.createStatement();
                int rs=stmt.executeUpdate("create table "+qname+"(number int,question varchar(1000),option1 varchar(50),option2 varchar(50),option3 varchar(50),option4 varchar(50),answer int,PRIMARY KEY(number))");
//                JOptionPane.showMessageDialog(null,"Ban Gayi");
            }catch(Exception e){ 
                JOptionPane.showMessageDialog(null, "Something Wrong!" + e);
            }
            String result = qname + "result";
            try{  
                Class.forName("com.mysql.jdbc.Driver");  
                java.sql.Connection con=DriverManager.getConnection( "jdbc:mysql://localhost:3306/resultquiz?zeroDateTimeBehavior=convertToNull","root","1234");  
                //here sonoo is database name, root is username and password  
                java.sql.Statement stmt=con.createStatement();
                int rs=stmt.executeUpdate("create table "+result+"(num int AUTO_INCREMENT,name varchar(50) NOT NUll,enroll varchar(12) NOT NUll,year varchar(15) NOT NUll,branch varchar(5),marks int,PRIMARY KEY(num))");
//                JOptionPane.showMessageDialog(null,"Ban Gayi");
            }catch(Exception e){ 
                JOptionPane.showMessageDialog(null, "Something Wrong!" + e);
                new login().setVisible(true);
                dispose();
            }
        new questionframe(qname).setVisible(true);
        
        
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String sendquiz  = (String) scorecombo.getSelectedItem();
        new scoreframe(sendquiz).setVisible(true);
             dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void scorecomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scorecomboActionPerformed
        
    }//GEN-LAST:event_scorecomboActionPerformed

    private void deletecomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletecomboActionPerformed
          String delname = (String) scorecombo1.getSelectedItem();
          String delresult = delname + "result";
          try{  
                Class.forName("com.mysql.jdbc.Driver");  
                java.sql.Connection con=DriverManager.getConnection( "jdbc:mysql://localhost:3306/admin?zeroDateTimeBehavior=convertToNull","root","1234");  
                //here sonoo is database name, root is username and password  
                java.sql.Statement stmt=con.createStatement();
                int rs=stmt.executeUpdate("Drop table "+delname+"");
                JOptionPane.showMessageDialog(null,"Successfully Deleted!");
            }catch(Exception e){ 
                JOptionPane.showMessageDialog(null, "Something Wrong!" + e);
            }
          try{  
                Class.forName("com.mysql.jdbc.Driver");  
                java.sql.Connection con=DriverManager.getConnection( "jdbc:mysql://localhost:3306/resultquiz?zeroDateTimeBehavior=convertToNull","root","1234");  
                //here sonoo is database name, root is username and password  
                java.sql.Statement stmt=con.createStatement();
                int rs=stmt.executeUpdate("Drop table "+delresult+"");
                JOptionPane.showMessageDialog(null,"Successfully Deleted!");
            }catch(Exception e){ 
                JOptionPane.showMessageDialog(null, "Something Wrong!" + e);
            }
          
         try{
        scorecombo1.removeAllItems();
        Class.forName("com.mysql.jdbc.Driver");  
        java.sql.Connection con=DriverManager.getConnection( "jdbc:mysql://localhost:3306/admin?zeroDateTimeBehavior=convertToNull","root","1234");  
        java.sql.Statement stmt=con.createStatement();
        ResultSet rs = null;  
        rs = stmt.executeQuery("SELECT table_name FROM information_schema.tables where table_schema='admin';");
        while (rs.next()) {
        String nm = rs.getString("table_name");
        scorecombo1.addItem(nm);
        }
      }catch(Exception e){
          JOptionPane.showMessageDialog(null,"Something Went Wrong!");
      }
    }//GEN-LAST:event_deletecomboActionPerformed

    private void scorecombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scorecombo1ActionPerformed
        
    }//GEN-LAST:event_scorecombo1ActionPerformed

    private void scorecomboComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_scorecomboComponentAdded
        
    }//GEN-LAST:event_scorecomboComponentAdded

    private void scorecomboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scorecomboMouseClicked
     
    }//GEN-LAST:event_scorecomboMouseClicked

    private void scorecombo1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_scorecombo1KeyPressed
        
    }//GEN-LAST:event_scorecombo1KeyPressed

    private void scorecombo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scorecombo1MouseClicked
       
    }//GEN-LAST:event_scorecombo1MouseClicked

    private void deletecomboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletecomboMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_deletecomboMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminlogopanel;
    private javax.swing.JButton check;
    private javax.swing.JPanel checkscore;
    private javax.swing.JButton create;
    private javax.swing.JPanel createquiz;
    private javax.swing.JButton delete;
    private javax.swing.JButton deletecombo;
    private javax.swing.JPanel deletequiz;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField quizname;
    private javax.swing.JComboBox scorecombo;
    private javax.swing.JComboBox scorecombo1;
    // End of variables declaration//GEN-END:variables
}
