/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quizango;

import java.awt.Panel;
import java.awt.event.KeyEvent;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Ram
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
//        start(adminpanel,studentpanel,logopanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        logopanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        adminpanel = new javax.swing.JPanel();
        password = new javax.swing.JPasswordField();
        username = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        studentpanel = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rolls = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        code = new javax.swing.JTextField();
        branchcombo = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        yearcombo = new javax.swing.JComboBox();
        jPanel8 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        stulogin = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(96, 223, 170));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 204, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, 50, 40));

        jLabel4.setFont(new java.awt.Font("Gisha", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LetsQUIZ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 40));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1100, 40);

        jPanel4.setBackground(new java.awt.Color(0, 204, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN As");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 310, -1));

        jPanel5.setBackground(new java.awt.Color(255, 102, 102));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("STUDENT");
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 200, 40));

        jPanel6.setBackground(new java.awt.Color(255, 102, 102));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("ADMIN");
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 200, 40));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizango/icons8-todo-list-100.png"))); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 310, 160));

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 90, 310, 410);

        logopanel.setBackground(new java.awt.Color(0, 204, 153));
        logopanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon("H:\\Downloads\\4c7e734e-caca-4a66-afa1-579f9e3fd737_200x200.png")); // NOI18N
        logopanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 410));

        jPanel1.add(logopanel);
        logopanel.setBounds(410, 90, 690, 410);

        adminpanel.setBackground(new java.awt.Color(0, 204, 153));
        adminpanel.setVisible(false);
        adminpanel.setLayout(null);

        password.setBackground(new java.awt.Color(0, 204, 153));
        password.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        password.setForeground(new java.awt.Color(255, 102, 102));
        password.setBorder(null);
        adminpanel.add(password);
        password.setBounds(420, 210, 240, 30);

        username.setBackground(new java.awt.Color(0, 204, 153));
        username.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        username.setForeground(new java.awt.Color(255, 102, 102));
        username.setBorder(null);
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        adminpanel.add(username);
        username.setBounds(420, 110, 240, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizango/icons8-admin-settings-male-64.png"))); // NOI18N
        adminpanel.add(jLabel7);
        jLabel7.setBounds(100, 120, 70, 70);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ADMIN");
        adminpanel.add(jLabel3);
        jLabel3.setBounds(90, 200, 86, 29);

        jLabel8.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Password");
        adminpanel.add(jLabel8);
        jLabel8.setBounds(290, 220, 97, 25);

        jLabel9.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Username");
        adminpanel.add(jLabel9);
        jLabel9.setBounds(290, 120, 99, 25);

        jPanel7.setBackground(new java.awt.Color(255, 102, 102));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("LOGIN");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 40));

        adminpanel.add(jPanel7);
        jPanel7.setBounds(360, 320, 190, 40);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("______________________");
        adminpanel.add(jLabel23);
        jLabel23.setBounds(420, 220, 242, 30);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("______________________");
        adminpanel.add(jLabel24);
        jLabel24.setBounds(420, 122, 242, 20);

        jPanel1.add(adminpanel);
        adminpanel.setBounds(410, 90, 690, 410);

        studentpanel.setBackground(new java.awt.Color(0, 204, 153));
        studentpanel.setVisible(false);
        studentpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizango/icons8-student-male-64.png"))); // NOI18N
        studentpanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 70, 70));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Enrollment");
        studentpanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, 30));

        rolls.setBackground(new java.awt.Color(0, 204, 154));
        rolls.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rolls.setForeground(new java.awt.Color(255, 0, 102));
        rolls.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rolls.setBorder(null);
        rolls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollsActionPerformed(evt);
            }
        });
        rolls.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rollsKeyTyped(evt);
            }
        });
        studentpanel.add(rolls, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 80, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Year");
        studentpanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 60, 40));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("_______");
        studentpanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 90, 30));

        Name.setBackground(new java.awt.Color(0, 204, 154));
        Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 0, 102));
        Name.setBorder(null);
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NameKeyTyped(evt);
            }
        });
        studentpanel.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 240, 30));

        code.setBackground(new java.awt.Color(0, 204, 154));
        code.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        code.setForeground(new java.awt.Color(255, 0, 102));
        code.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        code.setBorder(null);
        code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeActionPerformed(evt);
            }
        });
        code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codeKeyTyped(evt);
            }
        });
        studentpanel.add(code, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 70, 30));

        branchcombo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        branchcombo.setForeground(new java.awt.Color(0, 204, 104));
        branchcombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Branch", "CS", "IT", "ME", "CE", "EC" }));
        studentpanel.add(branchcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 90, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("______________________");
        studentpanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 250, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("______");
        studentpanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 70, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Name");
        studentpanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, 30));

        yearcombo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        yearcombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Year", "First Year", "Second Year", "Third Year", "Fourth Year" }));
        studentpanel.add(yearcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 240, 40));

        jPanel8.setBackground(new java.awt.Color(255, 102, 102));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("LOGIN");
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        studentpanel.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 200, 40));

        stulogin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        stulogin.setForeground(new java.awt.Color(255, 255, 255));
        stulogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stulogin.setText("STUDENT");
        stulogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        studentpanel.add(stulogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 200, 40));

        Email.setBackground(new java.awt.Color(0, 204, 154));
        Email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Email.setForeground(new java.awt.Color(255, 0, 102));
        Email.setBorder(null);
        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        Email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EmailKeyTyped(evt);
            }
        });
        studentpanel.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 240, 30));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("E-mail");
        studentpanel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, 30));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("______________________");
        studentpanel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 250, 30));

        jPanel1.add(studentpanel);
        studentpanel.setBounds(410, 90, 690, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1100, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
  
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        adminpanel.setVisible(true);
        studentpanel.setVisible(false);
        logopanel.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        adminpanel.setVisible(false);
        studentpanel.setVisible(true);
        logopanel.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed
    int s=0;    int l=0;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String user = username.getText();
        int pass = Integer.parseInt(password.getText());
        if(user.equals("admin@123") && pass==1234){
            new adminmenu().setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(null,"Invalid Username or Password!");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String name =  Name.getText();
        String cod = code.getText();
        String roll = rolls.getText();
        String branch = (String) branchcombo.getSelectedItem();
        String years = (String) yearcombo.getSelectedItem();
        
        String eroll= cod + branch + roll;
        new studentmenu(name,eroll,branch,years).setVisible(true);
//        name,eroll,branch,year
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void codeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codeKeyTyped
        int ccod = evt.getKeyChar();
        if(s>3){
            s = 3;
            evt.consume();
            getToolkit().beep();
        }
        if((evt.getKeyChar() == KeyEvent.VK_BACK_SPACE || evt.getKeyChar() == KeyEvent.VK_DELETE) && s>0){
//            System.out.println("Back   " + s);
            --s;
        }
        if(!(Character.isDigit(ccod))){
            evt.consume();
            getToolkit().beep();
        }else{
            s++;
        }
    }//GEN-LAST:event_codeKeyTyped

    private void codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeActionPerformed

    private void NameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameKeyTyped
       char a = evt.getKeyChar();
       if((Character.isDigit(a))){
           evt.consume();
           getToolkit().beep();
       }
    }//GEN-LAST:event_NameKeyTyped

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void rollsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rollsKeyTyped
        int ccod = evt.getKeyChar();
        if(l>5){
            l = 5;
            evt.consume();
            getToolkit().beep();
        }
        if((evt.getKeyChar() == KeyEvent.VK_BACK_SPACE || evt.getKeyChar() == KeyEvent.VK_DELETE) && l>0){
//            System.out.println("Back   " + s);
            --l;
        }
        if(!(Character.isDigit(ccod))){
            evt.consume();
            getToolkit().beep();
        }else{
            l++;
        }
    }//GEN-LAST:event_rollsKeyTyped

    private void rollsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rollsActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void EmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmailKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailKeyTyped
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Name;
    private javax.swing.JPanel adminpanel;
    private javax.swing.JComboBox branchcombo;
    private javax.swing.JTextField code;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel logopanel;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField rolls;
    private javax.swing.JPanel studentpanel;
    private javax.swing.JLabel stulogin;
    private javax.swing.JTextField username;
    private javax.swing.JComboBox yearcombo;
    // End of variables declaration//GEN-END:variables

    private void start(JPanel adminpanel, JPanel studentpanel, JPanel logopanel) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
