/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quizango;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/**
 *
 * @author Ram
 */

public class questionframe extends javax.swing.JFrame {
    private String qname;
    public String quizname;
    /**
     * Creates new for
     */
    public questionframe() {
        initComponents();
    }
    public questionframe(String quname){
        initComponents();
        quizname = quname;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        qut1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        qut2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        qut3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        qut4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        qut5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        qut6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        qut7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        qut8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        qut9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        qut10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        panelQ1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        question = new javax.swing.JTextField();
        opt4 = new javax.swing.JTextField();
        opt3 = new javax.swing.JTextField();
        opt2 = new javax.swing.JTextField();
        opt1 = new javax.swing.JTextField();
        questionnumber = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        answer1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        update = new javax.swing.JButton();
        publish = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        publishing = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(96, 223, 170));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 204, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        qut1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("1");
        qut1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 30));

        jPanel2.add(qut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 50, 50));

        qut2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("2");
        qut2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 30));

        jPanel2.add(qut2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 50, 50));

        qut3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("3");
        qut3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 30));

        jPanel2.add(qut3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 50, 50));

        qut4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("4");
        qut4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 30));

        jPanel2.add(qut4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 50, 50));

        qut5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("5");
        qut5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 30));

        jPanel2.add(qut5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 50, 50));

        qut6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("6");
        qut6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 30));

        jPanel2.add(qut6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 50, 50));

        qut7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("7");
        qut7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 30));

        jPanel2.add(qut7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 50, 50));

        qut8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("8");
        qut8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 30));

        jPanel2.add(qut8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 50, 50));

        qut9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("9");
        qut9.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 30));

        jPanel2.add(qut9, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 50, 50));

        qut10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("10");
        qut10.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 30));

        jPanel2.add(qut10, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 50, 50));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 20, 1100, 50);

        panelQ1.setBackground(new java.awt.Color(0, 204, 153));
        panelQ1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tekton Pro", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Enter Correct Answer");
        panelQ1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 390, -1));

        question.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        question.setToolTipText("Enter");
        question.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        question.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionActionPerformed(evt);
            }
        });
        panelQ1.add(question, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 940, 50));

        opt4.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        panelQ1.add(opt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, 350, 40));

        opt3.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        panelQ1.add(opt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 350, 40));

        opt2.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        panelQ1.add(opt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 350, 40));

        opt1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        panelQ1.add(opt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 350, 40));

        questionnumber.setFont(new java.awt.Font("Tekton Pro", 1, 36)); // NOI18N
        questionnumber.setForeground(new java.awt.Color(255, 255, 255));
        questionnumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        questionnumber.setText("1");
        panelQ1.add(questionnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 50, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("3.");
        panelQ1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 30, 40));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("2.");
        panelQ1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 30, 40));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("4.");
        panelQ1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 30, 40));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("1.");
        panelQ1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 30, 40));

        answer1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        answer1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        answer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer1ActionPerformed(evt);
            }
        });
        answer1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                answer1KeyTyped(evt);
            }
        });
        panelQ1.add(answer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 90, 40));

        jLabel13.setFont(new java.awt.Font("Tekton Pro", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Enter Options");
        panelQ1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1040, -1));

        jLabel19.setText("Enter Option Number Only eg. 1,2,3 or 4");
        panelQ1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 210, 20));

        jLabel20.setFont(new java.awt.Font("Tekton Pro", 1, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Enter Question :");
        panelQ1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 20, 260, -1));

        jPanel9.setBackground(new java.awt.Color(255, 102, 102));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        update.setBackground(new java.awt.Color(255, 255, 255));
        update.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Update");
        update.setBorderPainted(false);
        update.setContentAreaFilled(false);
        update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel9.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 40));

        panelQ1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 340, 190, 40));

        jPanel1.add(panelQ1);
        panelQ1.setBounds(30, 150, 1040, 400);

        publish.setBackground(new java.awt.Color(0, 204, 153));
        publish.setVisible(false);
        publish.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(255, 102, 102));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        publishing.setBackground(new java.awt.Color(255, 255, 255));
        publishing.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        publishing.setForeground(new java.awt.Color(255, 255, 255));
        publishing.setText("Publish Quiz");
        publishing.setBorderPainted(false);
        publishing.setContentAreaFilled(false);
        publishing.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        publishing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publishingActionPerformed(evt);
            }
        });
        jPanel10.add(publishing, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 40));

        publish.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 320, 40));

        jPanel1.add(publish);
        publish.setBounds(30, 150, 1040, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1100, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void questionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_questionActionPerformed

    private void answer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer1ActionPerformed
    int l=0;
    private void answer1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_answer1KeyTyped
        int ccod = evt.getKeyChar();
        if((evt.getKeyChar() == KeyEvent.VK_BACK_SPACE || evt.getKeyChar() == KeyEvent.VK_DELETE) && l>0){
            --l;
        }
        if(l>0){
            l = 0;
            evt.consume();
            getToolkit().beep();
        }
        else if(!(Character.isDigit(ccod))){
            evt.consume();
            getToolkit().beep();
        }else{
            l++;
//            System.out.println(ccod);
        }
    }//GEN-LAST:event_answer1KeyTyped
    int qnumber = 1;
    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        String ques = question.getText();
        String op1 = opt1.getText();
        String op2 = opt2.getText();
        String op3 = opt3.getText();
        String op4 = opt4.getText();
        int ans = Integer.parseInt(answer1.getText());
        
        
        
        
        try{  
                Class.forName("com.mysql.jdbc.Driver");  
                java.sql.Connection con=DriverManager.getConnection( "jdbc:mysql://localhost:3306/admin?zeroDateTimeBehavior=convertToNull","root","12345");  
                //here sonoo is database name, root is username and password  
                java.sql.Statement stmt=con.createStatement();
                if(qnumber<=10){
                   
                    int rs=stmt.executeUpdate("insert into "+quizname+"(number,question,option1,option2,option3,option4,answer) values "
                            + "('"+qnumber+"','"+ques+"','"+op1+"','"+op2+"','"+op3+"','"+op4+"','"+ans+"')");  
                               qnumber++;
                    JOptionPane.showMessageDialog(null,"Succesfully Added!");
                    String show=String.valueOf(qnumber);
                    questionnumber.setText(show);
                    if(qnumber==2)qut1.setBackground(Color.red);
                    if(qnumber==3)qut2.setBackground(Color.red);
                    if(qnumber==4)qut3.setBackground(Color.red);
                    if(qnumber==5)qut4.setBackground(Color.red);
                    if(qnumber==6)qut5.setBackground(Color.red);
                    if(qnumber==7)qut6.setBackground(Color.red);
                    if(qnumber==8)qut7.setBackground(Color.red);
                    if(qnumber==9)qut8.setBackground(Color.red);
                    if(qnumber==10)qut9.setBackground(Color.red);
                    if(qnumber==11)qut10.setBackground(Color.red);
                    if(qnumber==11){
                        publish.setVisible(true);
                        panelQ1.setVisible(false);
                    }
                }
            }catch(Exception e){ 
                JOptionPane.showMessageDialog(null, "Something Wrong!" + e);
            } 
        
        question.setText("");
        opt1.setText("");
        opt2.setText("");
        opt3.setText("");
        opt4.setText("");
        answer1.setText("");
         
    }//GEN-LAST:event_updateActionPerformed

    private void publishingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publishingActionPerformed
        new adminmenu().setVisible(true);
        dispose();
    }//GEN-LAST:event_publishingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(questionframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(questionframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(questionframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(questionframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new questionframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answer1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField opt1;
    private javax.swing.JTextField opt2;
    private javax.swing.JTextField opt3;
    private javax.swing.JTextField opt4;
    private javax.swing.JPanel panelQ1;
    private javax.swing.JPanel publish;
    private javax.swing.JButton publishing;
    private javax.swing.JTextField question;
    private javax.swing.JLabel questionnumber;
    private javax.swing.JPanel qut1;
    private javax.swing.JPanel qut10;
    private javax.swing.JPanel qut2;
    private javax.swing.JPanel qut3;
    private javax.swing.JPanel qut4;
    private javax.swing.JPanel qut5;
    private javax.swing.JPanel qut6;
    private javax.swing.JPanel qut7;
    private javax.swing.JPanel qut8;
    private javax.swing.JPanel qut9;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
