/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quizango;

import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Ram
 */
public class studentmenu extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    public studentmenu() {
        initComponents();
    }
    String sname,sroll,sbranch,syear;
    public studentmenu(String Name,String Eroll,String Branch,String Year){
        initComponents();
        sname = Name;
        sroll = Eroll;
        sbranch = Branch;
        syear = Year;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        adminlogopanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        guizselect = new javax.swing.JButton();
        selectquizstudent = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        quizattemp = new javax.swing.JComboBox();
        jPanel10 = new javax.swing.JPanel();
        go = new javax.swing.JButton();
        instruction = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        go2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(96, 223, 170));
        adminlogopanel.setVisible(true);
        selectquizstudent.setVisible(false);
        instruction.setVisible(false);
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 204, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, 50, 40));

        jLabel4.setFont(new java.awt.Font("Gisha", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LetsQUIZ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 40));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1100, 40);

        jPanel4.setBackground(new java.awt.Color(0, 204, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("STUDENT");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 270, -1));

        jPanel6.setBackground(new java.awt.Color(255, 102, 102));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LetsQUIZ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 270, 40));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizango/icons8-admin-settings-male-64.png"))); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 270, 100));

        jPanel8.setBackground(new java.awt.Color(255, 102, 102));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Select Quiz");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 270, 40));

        jPanel7.setBackground(new java.awt.Color(255, 102, 102));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Instruction & Start");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 270, 40));

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 90, 270, 410);

        adminlogopanel.setBackground(new java.awt.Color(0, 204, 153));
        adminlogopanel.setVisible(true);
        adminlogopanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon("H:\\Downloads\\4c7e734e-caca-4a66-afa1-579f9e3fd737_200x200.png")); // NOI18N
        adminlogopanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 690, 250));

        jPanel12.setBackground(new java.awt.Color(255, 102, 102));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        guizselect.setBackground(new java.awt.Color(255, 255, 255));
        guizselect.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        guizselect.setForeground(new java.awt.Color(255, 255, 255));
        guizselect.setText("Select quiz");
        guizselect.setBorderPainted(false);
        guizselect.setContentAreaFilled(false);
        guizselect.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guizselect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guizselectActionPerformed(evt);
            }
        });
        jPanel12.add(guizselect, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 40));

        adminlogopanel.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 190, 40));

        jPanel1.add(adminlogopanel);
        adminlogopanel.setBounds(410, 90, 690, 410);

        selectquizstudent.setBackground(new java.awt.Color(0, 204, 153));
        adminlogopanel.setVisible(false);
        selectquizstudent.setVisible(true);
        instruction.setVisible(false);
        selectquizstudent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizango/icons8-single-choice-80.png"))); // NOI18N
        selectquizstudent.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 80, 80));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Select a QUIZ to Attempt");
        selectquizstudent.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("SELECT QUIZ");
        selectquizstudent.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        quizattemp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        quizattemp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Quiz", "scheck" }));
        quizattemp.setBorder(null);
        try{
            quizattemp.removeAllItems();
            Class.forName("com.mysql.jdbc.Driver");
            java.sql.Connection con=DriverManager.getConnection( "jdbc:mysql://localhost:3306/admin?zeroDateTimeBehavior=convertToNull","root","12345");
            java.sql.Statement stmt=con.createStatement();
            ResultSet rs = null;
            rs = stmt.executeQuery("SELECT table_name FROM information_schema.tables where table_schema='admin';");
            while (rs.next()){
                String nm = rs.getString("table_name");
                quizattemp.addItem(nm);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Sorry!");
        }
        quizattemp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quizattempMouseClicked(evt);
            }
        });
        quizattemp.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                quizattempComponentAdded(evt);
            }
        });
        quizattemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quizattempActionPerformed(evt);
            }
        });
        selectquizstudent.add(quizattemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 260, 40));

        jPanel10.setBackground(new java.awt.Color(255, 102, 102));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        go.setBackground(new java.awt.Color(255, 255, 255));
        go.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        go.setForeground(new java.awt.Color(255, 255, 255));
        go.setText("GO");
        go.setBorderPainted(false);
        go.setContentAreaFilled(false);
        go.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goActionPerformed(evt);
            }
        });
        jPanel10.add(go, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 40));

        selectquizstudent.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 190, 40));

        jPanel1.add(selectquizstudent);
        selectquizstudent.setBounds(410, 90, 690, 410);

        instruction.setBackground(new java.awt.Color(0, 204, 153));
        instruction.setVisible(false);
        instruction.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizango/icons8-user-manual-96.png"))); // NOI18N
        instruction.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 110, 90));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("INSTRUCTION");
        instruction.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 255, 255));
        jLabel12.setText("submitted & for remaining question you will get 0 marks.");
        instruction.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 440, 30));

        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 255, 255));
        jLabel13.setText("1. Quiz will be open for 10 minute, After than It automatically");
        instruction.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 440, 30));

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 255, 255));
        jLabel14.setText("2. Each Question consist of Four Option and Only one correct");
        instruction.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 440, 30));

        jLabel15.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 255, 255));
        jLabel15.setText("1 marks and No negative marks for Wrong Answer.");
        instruction.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 360, 30));

        jLabel17.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 255, 255));
        jLabel17.setText("answer. For each correct answer you will be awarded by");
        instruction.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 390, 30));

        jPanel11.setBackground(new java.awt.Color(255, 102, 102));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        go2.setBackground(new java.awt.Color(255, 255, 255));
        go2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        go2.setForeground(new java.awt.Color(255, 255, 255));
        go2.setText("Start");
        go2.setBorderPainted(false);
        go2.setContentAreaFilled(false);
        go2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        go2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                go2ActionPerformed(evt);
            }
        });
        jPanel11.add(go2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 40));

        instruction.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 190, 40));

        jPanel1.add(instruction);
        instruction.setBounds(410, 90, 690, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1100, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void quizattempMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quizattempMouseClicked

    }//GEN-LAST:event_quizattempMouseClicked

    private void quizattempComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_quizattempComponentAdded

    }//GEN-LAST:event_quizattempComponentAdded

    private void quizattempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quizattempActionPerformed

    }//GEN-LAST:event_quizattempActionPerformed
    public String finalname;
    private void goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goActionPerformed
        adminlogopanel.setVisible(false);
        selectquizstudent.setVisible(false);
        instruction.setVisible(true);
        
        String qnames = (String)quizattemp.getSelectedItem();
        finalname = qnames;
//        System.out.print(finalname);
//        System.out.print(sname);
        String addtotable = qnames + "result";
        
        
        
        
        try{  
                Class.forName("com.mysql.jdbc.Driver");  
                java.sql.Connection con=DriverManager.getConnection( "jdbc:mysql://localhost:3306/resultquiz?zeroDateTimeBehavior=convertToNull","root","12345");  
                //here sonoo is database name, root is username and password  
                java.sql.Statement stmt=con.createStatement();
                int rs=stmt.executeUpdate("insert into "+addtotable+"(name,enroll,year,branch) values ('"+sname+"','"+sroll+"','"+syear+"','"+sbranch+"')");  
            }catch(Exception e){ 
                System.out.print(e);
                JOptionPane.showMessageDialog(null, "Something Wrong!");
                
            } 
        
        
        
        
        
        instruction.setVisible(true);
        
       
        
    }//GEN-LAST:event_goActionPerformed

    private void go2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_go2ActionPerformed
        String setName = finalname;
        new studentquestion(setName,sroll).setVisible(true);
        dispose();
    }//GEN-LAST:event_go2ActionPerformed

    private void guizselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guizselectActionPerformed
        adminlogopanel.setVisible(false);
        selectquizstudent.setVisible(true);
        instruction.setVisible(false);
    }//GEN-LAST:event_guizselectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminlogopanel;
    private javax.swing.JButton go;
    private javax.swing.JButton go2;
    private javax.swing.JButton guizselect;
    private javax.swing.JPanel instruction;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JComboBox quizattemp;
    private javax.swing.JPanel selectquizstudent;
    // End of variables declaration//GEN-END:variables
}
